/**
 * Build responsive `srcset` strings (WebP and AVIF) from a single master URL.
 *
 * Used in `<picture><source srcSet={...} type="image/(avif|webp)">` so the
 * browser picks the right physical-pixel size based on viewport + DPR,
 * and the right format based on Accept header support (AVIF first, WebP
 * fallback).
 *
 * Variants are generated by scripts/generate-image-variants.mjs which walks
 * public/pics* and emits -400/-800/-1200/-1600/-2400w in BOTH .webp and
 * .avif for every master at sufficient resolution.
 *
 * Why AVIF (Batch 40): -25-30% wire bytes vs WebP at the same visual
 * quality. Used by Sézane (via Cloudinary), Polène (Shopify), Cuyana
 * (Shopify Image API). 96%+ of modern browsers support AVIF — the rest
 * gracefully fall back to the WebP source.
 *
 * Why master @ 3200w (Batch 40): retina desktop (1920×2 DPR = 3840 phys
 * px) and 4K iMac need ≥3200w master to avoid upscale-blur. The browser's
 * srcset selector picks the smallest candidate ≥ physical-pixel demand,
 * so:
 *   mobile (390×3 = 1170 phys px)    → 1200w variant
 *   tablet (768×2 = 1536 phys px)    → 1600w variant
 *   desktop 1920×2 retina at 100vw   → 2400w variant
 *   desktop 4K retina full-bleed     → master (3200w slot)
 *
 * For masters smaller than 1200w the -1200w.{webp,avif} won't exist on
 * disk → that srcset entry 404s when the browser tries to load it.
 * Browser then picks the next-closest available width. Net effect: one
 * wasted HEAD request in the rare narrow-master case, no broken UI.
 */

/**
 * Variant widths that the generator emits IF the master is wide enough.
 * For an image with natural width 2000px, only -400/-800/-1200/-1600w
 * variants exist on disk — -2400w would be silently skipped at gen
 * time because we don't upscale.
 *
 * Critical: srcset entries that point to non-existent variant files
 * break `<picture>` rendering on Chrome — the browser picks the closest
 * descriptor, hits 404, and refuses to fall back to the `<img>` src.
 * That's why this list stops at 1600w (the largest variant we
 * unconditionally generate for our 2000w-class hero masters) and we
 * use the master file itself as the high-end endpoint.
 *
 * The master is always written by the generator at min(natural, 3200w)
 * so it covers retina desktop / 4K demand even though the descriptor
 * we attach to it (2400w) is conservative.
 */
const VARIANT_WIDTHS = [400, 800, 1200, 1600];
const MASTER_WIDTH_DESCRIPTOR = 2400;

function stripExt(url: string): string {
    return url.replace(/\.(jpg|jpeg|JPG|JPEG|png|PNG|webp|avif)$/, "");
}

export function buildWebpSrcset(url: string): string {
    const base = stripExt(url);
    return [
        ...VARIANT_WIDTHS.map((w) => `${base}-${w}w.webp ${w}w`),
        // Master endpoint — file is ≤3200w wide; descriptor is 2400w so
        // the browser still picks it for ≥1600w displays.
        `${base}.webp ${MASTER_WIDTH_DESCRIPTOR}w`,
    ].join(", ");
}

/**
 * Mirror of buildWebpSrcset for AVIF. Both srcsets reference the same
 * masters / widths — the generator emits parallel .webp and .avif files.
 *
 * Place this <source> BEFORE the WebP one inside <picture> so the browser
 * picks AVIF first when supported.
 */
export function buildAvifSrcset(url: string): string {
    const base = stripExt(url);
    return [
        ...VARIANT_WIDTHS.map((w) => `${base}-${w}w.avif ${w}w`),
        `${base}.avif ${MASTER_WIDTH_DESCRIPTOR}w`,
    ].join(", ");
}
