/**
 * Build a `srcset` string of responsive webp width-variants from a
 * single master URL.  Used in `<picture><source srcSet={...}>` so the
 * browser can pick the right physical-pixel size based on viewport +
 * DPR.
 *
 * Variants are generated by scripts/generate-image-variants.mjs which
 * walks public/pics* and emits -400w.webp / -800w.webp / -1200w.webp
 * for every master > the target width.
 *
 * The master URL is included as the final entry with a 2400w descriptor.
 * This keeps the master in play for retina-desktop / hi-DPR displays
 * where a 1200w variant would be upscaled and look mushy. The browser's
 * srcset selector picks the smallest candidate ≥ physical-pixel demand,
 * so:
 *   mobile (390×3 = 1170 phys px)    → 1200w variant
 *   tablet (768×2 = 1536 phys px)    → 1200w variant
 *   desktop 1920×2 retina at 100vw   → master (2400w slot)
 *   desktop 4K retina                → master (2400w slot)
 *
 * For masters smaller than 1200w the -1200w.webp won't exist on disk
 * → that srcset entry 404s when the browser tries to load it.  Browser
 * then picks the next-closest available width.  Net effect: one
 * wasted HEAD request in the rare narrow-master case, no broken UI.
 */
export function buildWebpSrcset(url: string): string {
    // Strip any extension (jpg/jpeg/png/webp) — variants are always .webp.
    const base = url.replace(/\.(jpg|jpeg|JPG|JPEG|png|PNG)$/, ".webp").replace(/\.webp$/, "");
    return [
        `${base}-400w.webp 400w`,
        `${base}-800w.webp 800w`,
        `${base}-1200w.webp 1200w`,
        `${base}-1600w.webp 1600w`,
        `${base}-2000w.webp 2000w`,
        `${base}.webp 2400w`, // master fallback for 4K+ retina
    ].join(", ");
}
