/**
 * Build a `srcset` string of responsive webp width-variants from a
 * single master URL.  Used in `<picture><source srcSet={...}>` so the
 * browser can pick the right physical-pixel size based on viewport +
 * DPR.
 *
 * Variants are generated by scripts/generate-image-variants.mjs which
 * walks public/pics* and emits -400w.webp / -800w.webp / -1200w.webp
 * for every master > the target width.
 *
 * For masters smaller than 1200w the -1200w.webp won't exist on disk
 * → that srcset entry 404s when the browser tries to load it.  Browser
 * then picks the next-closest available width.  Net effect: one
 * wasted HEAD request in the rare narrow-master case, no broken UI.
 */
export function buildWebpSrcset(url: string): string {
    // Strip any extension (jpg/jpeg/png/webp) — variants are always .webp.
    const base = url.replace(/\.(jpg|jpeg|JPG|JPEG|png|PNG)$/, ".webp").replace(/\.webp$/, "");
    return `${base}-400w.webp 400w, ${base}-800w.webp 800w, ${base}-1200w.webp 1200w`;
}
