// Merge scripts/i18n/ui-strings/*.json into the generated dictionary modules
// app/i18n/dictionaries/{en,ru}.generated.ts.
//
// Each part file has the shape:
//   { "<ukrainian source string>": { "en": "...", "ru": "..." }, ... }
// Conflicting keys must carry identical translations — otherwise the merge
// fails loudly (two agents translating one string differently is a bug to
// resolve by hand, not to last-write-win silently).
//
// Usage: node scripts/i18n/build-dicts.mjs
import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const partsDir = join(here, "ui-strings");
const outDir = join(here, "..", "..", "app", "i18n", "dictionaries");

if (!existsSync(partsDir)) {
    console.error(`No parts dir: ${partsDir}`);
    process.exit(1);
}

const merged = {}; // key -> {en, ru, from}
let conflictCount = 0;

for (const file of readdirSync(partsDir)
    .filter((f) => f.endsWith(".json"))
    .sort()) {
    const part = JSON.parse(readFileSync(join(partsDir, file), "utf8"));
    for (const [key, val] of Object.entries(part)) {
        if (!val || typeof val.en !== "string" || typeof val.ru !== "string") {
            console.error(`[${file}] bad entry for key: ${key}`);
            process.exitCode = 1;
            continue;
        }
        const prev = merged[key];
        if (prev && (prev.en !== val.en || prev.ru !== val.ru)) {
            console.error(
                `CONFLICT "${key}"\n  ${prev.from}: en="${prev.en}" ru="${prev.ru}"\n  ${file}: en="${val.en}" ru="${val.ru}"`,
            );
            conflictCount++;
            continue;
        }
        merged[key] = { ...val, from: file };
    }
}

if (conflictCount > 0) {
    console.error(`${conflictCount} conflicts — resolve in the part files, then re-run.`);
    process.exit(1);
}

const keys = Object.keys(merged).sort((a, b) => a.localeCompare(b, "uk"));

function emit(locale) {
    const lines = keys.map(
        (k) => `    ${JSON.stringify(k)}: ${JSON.stringify(merged[k][locale])},`,
    );
    return `// AUTO-GENERATED by scripts/i18n/build-dicts.mjs — do not edit by hand.
// Source of truth: scripts/i18n/ui-strings/*.json (one file per UI module).
// Keys are exact Ukrainian source strings; see app/i18n/index.tsx.
/* eslint-disable */
export const ${locale}Generated: Record<string, string> = {
${lines.join("\n")}
};
`;
}

writeFileSync(join(outDir, "en.generated.ts"), emit("en"), "utf8");
writeFileSync(join(outDir, "ru.generated.ts"), emit("ru"), "utf8");
console.info(`built ${keys.length} keys → en.generated.ts / ru.generated.ts`);
